### ISSUE TITLE
Version 4.6 sequel

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#202]
Since we have advanced the story of the second half of Ver 4.6, we will add keywords. This time, I am creating it from Genshin Impact's "Archive" - "Travel Log". Also, I'm sorry, but I'm including typo and those that were found to be misread.

Charactor of Fonraine

| English | Japanese | Chinese Simplifed | Note(ja) | Type | memo |
|---|---|---|---|---|---|
|Rene de Petrichor|ルネ・ド・ペトリコール|雷内·德·佩特莉可|ナルツィッセンクロイツの人間時代の名前| NPC |ちなみにHoYoverse公式壁紙アプリのN0va Desktopに"Below the Dust"というタイトルでフューチャーされている|
|Mary-Ann Guillotin|マリアン・ギヨタン|玛丽安·吉约丹|純水精霊のマリアンとは別人格| NPC |
|Lyris|リリス|莉利丝||NPC|
|Cassiodor|カッシオドル|卡西奥多||NPC|Sorry. typo(engilish)|

Charactor of Sumeru

| English | Japanese | Chinese Simplifed | Note(ja) | Type | memo |
|---|---|---|---|---|---|
|Cyrus|ジュライセン|居勒什|| NPC |
|Naphis|ナフィス|纳菲斯|| NPC |
|-|ザハハディ||| NPC | ※入力済み
|Aarav|アーラヴ|阿拉夫|| NPC |
|-|セトス||| Playable | ※入力済み
|Bamoun|バムーン|巴穆恩|| NPC |
|?|ウラカ||| NPC |？入力の価値あり？
|?|ドゥアンレ||| NPC |？入力の価値あり？
|?|チャーミアン||| NPC |？入力の価値あり？
|?|アンテフ||| NPC |？入力の価値あり？
|-|ヘルマヌビス||| NPC | ※入力済み

Charactor of ???

| English | Japanese | Chinese Simplifed | Note(ja) | Type |
|---|---|---|---|---|
|Nicole Reeyn|ニコ・リヤン|尼可·莱恩|| NPC |

Event

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Odisseia da Fortaleza Felina|モフモフの城にゃん冒険|茸茸城堡大喵险|Ver.4.5限定イベント||
|Windtrace: Seekers and Strategy|風の行方・妙策の陣|风行迷踪・谋策之局|Ver.4.6限定イベント||
|Iridescent Arataki Rockin' for Life Tour de Force of Awesomeness|荒瀧・生命のロックイリデッセンスビッグツアー|荒泷生命摇滚虹色大巡回|Ver.4.6限定イベント||

Location of Sumeru

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Tulaytullah|トゥライトゥーラ|图莱杜拉||セノ 伝説任務 金狼の章第二幕より判明|

Object of Sumeru

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|BA Fragment|跋霊(ばつれい)|跋灵|ヘルマヌビスの力の破片|セノ 伝説任務 金狼の章第二幕より判明。英語発音では"BA"をそのまま「ば」と発音しているので音感的に「ば+Fragment」としたのか？|

Organization of Sumeru

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|-|沈黙の殿(ちんもくのでん)|||※入力済み
|Tighnarians|ティナル人(ティナルじん)|提纳勒人||セノ 伝説任務 金狼の章第二幕より判明|
|Valka Shuna|ワルカシュナ|巴螺迦修那||セノ 伝説任務 金狼の章第二幕より判明|

Organization of Khaenri'ah

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Crimson Moon|赤月(せきげつ)|赤月|カールンイアの古代王朝|アルレッキーノ キャラクターストーリ5で判明。なお由来はカールンイアの人工月の模様|
|Eclipse|黒日(こくじつ)|黒日|カールンイアの古代王朝|アルレッキーノ キャラクターストーリ5で判明。なお由来はカールンイアの人工太陽の模様|

Item

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Ancient Autoharmonic Music Box|古いオルゴール|古老的自鸣音乐盒|||
|Nightwind Horn|ナイトウィンド・ホルン|晚风圆号|||
|Time Trekker|時の旅人|旅时者||Book|
|Perinheri|ペインヘリ|裴伦埃里||Book|
|Anecdota Septentrionalis|北方秘史|北境秘史||Book|
|The Two Musketeers|二銃士|两个铳枪手||Book and movie|
|"I Got Reincarnated as an Onikabuto... And Flipped the World Upside Down"|『最強オニカブトムシに転生して 世界をひっくり返してやった』|《转生成为鬼兜虫然后撞翻世界》|

Food

| English | Japanese | Chinese Simplifed | Note(ja) | 
|---|---|---|---|
|Fashion Show|ファッションショー|时装秀|千織のオリジナル料理|
|Sin: The Kind that Doesn't Need to be Dealt With|罪・対処不必要型(つみ・たいしょふひつようがた)|罪恶·非必要处理型|シュヴルーズのオリジナル料理|
|Rock 'n' Roll Dango Milk|ロック団子牛乳|摇滚团子牛奶|荒瀧・生命のロックイリデッセンスビッグツアーの屋台|

Weapon
| English | Japanese | Chinese Simplifed | Note(ja) |memo|
|---|---|---|---|---|
|Crimson Moon's Semblance|赤月のシルエット(せきげつのシルエット)|赤月之形||あかつき→せきげつに読み変更。アルレッキーノを知る・５のボイスで確認|

**Comment by xicri** [comment]
Looks good, please send a PR.

A few comments:

- Regarding to Arataki's song name (Reincarnated as an Onikabuto), I think it can be categorized as an event rather than items since it is not an item (Let me know if I missed something.) and related to the event.
- Regarding to Rock 'n' Roll Dango Milk, please store it in events.json5 and add both `food` and `event` tags.
- Mary-Ann Guillotin is already added with her first name. Please update the existing word to add her surname.
- Cyrus is already registered too.

Thanks as always!
