### ISSUE TITLE
Fix typos: Lo"a"d to Lo"r"d

### ISSUE THREAD

**Issue by tjq21** [xicri/genshin-langdata#216]
In the website, Lesser Lord Kusanali / 小吉祥草王 is mis-spelled as Lesser LOAD Kusanali, as shown in the screenshot below.
![Screenshot_20240608_133138_com.huawei.browser_edit_134313226222734.jpg](https://github.com/xicri/genshin-langdata/assets/104332893/3bfa4a79-72b8-499b-a9b9-c10db59a38d4)

**Comment by xicri** [comment]
Oops, I frequently misspell lord as load...
I will fix it. Thanks for the reporting!

**Comment by xicri** [comment]
Fix has been merged to the main branch and it will be deployed in 5-10 mins.

**Comment by tjq21** [comment]
Thanks for your effort.

Sorry to bother you again, as I've found several similar typos, which are

- Dragon Load's Crown / 龍王の冠 / 龙王之冕;
- Greater Load Rukkhadevata / マハールッカデヴァータ / 大慈树王; and
- Luxurious Sea-Load / 銜玉の海皇 / 衔珠海皇.

Thank you very much. ありがとうございます。

**Comment by xicri** [comment]
Oh no... 😱
Thanks, I will fix them.

**Comment by tjq21** [comment]
It seems that you are quite busy these days. Would you mind that I fork this repo and correct them? I'm willing to contribute :)

**Comment by xicri** [comment]
Yes, please. Thanks!
