### ISSUE TITLE
Add new keywords for Ver.4.7 sequel genshin-langdata

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#231]
Since we have advanced the story of the second half of Ver 4.7, we will add keywords. This time, I am creating it from Genshin Impact's "Archive" - "Travel Log".

Book(Item)

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|The Little Witch and the Undying Fire|小さな魔女と消えない炎|小魔女与不熄灭的火||| |
|The Feline Firm| ニャンコ事務所 | 猫咪事务所 ||| |

Charactor of Mondstadt

| English | Japanese | Chinese Simplifed | Note(ja) | Type |memo|
|---|---|---|---|---|---|
|入力済み|イノシシプリンセス|-|書籍もしくは幻想シアターの控え室の額縁の中で動き回るキャラクター|NPC| 書籍としては登録済み tags:[Character (NPC), Mondstadt] |
|Wolfy|子オオカミ|子狼|幻想シアターの控え室にに登場するキャラクター|NPC| |

Charactor of Fontaine

| English | Japanese | Chinese Simplifed | Note(ja) | Type |memo|
|---|---|---|---|---|---|
|Rawat|ラワット|拉瓦特|| NPC||
|Potton|ポトン|波顿|| NPC||
|Wolsey|ウォルジー|韦尔赛|| NPC | 登場自体はVer. 4.1メロピデ要塞実装時から。特別許可食堂の料理長|
|Bran|ブラン|布兰|| NPC| 登場自体はVer. 4.1メロピデ要塞実装時から。特別許可食堂のマシナリー|
|"The Witch"|「魔女婆さん」|「巫婆」|シグウィンを人間の姿に変える薬を作った医者の先生| NPC|tags:[how to call]|

Charactor of Liyue

| English | Japanese | Chinese Simplifed | Note(ja) | Type |memo|
|---|---|---|---|---|---|
|Hautemontague|オートモンターニュ|沃特蒙泰涅|| NPC|登場自体はVer.4.4から tags:[liyue, fontaine]|
|Mountain|大山(読み方不明)|大山|オートモンターニュの璃月での通称| NPC|必要? tags:[liyue, fontaine, how to call]|

Food

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Well-Balanced Meal|栄養たっぷりバランス食|膳食均衡餐|シグウィンのオリジナル料理|ちなみに3日続けて働いたときに提供される福祉食ではない|
|Super-Dee-Duper Delicious Meat Roll|ウマウマシャワルマサンド|烤肉香香香卷|セトスのオリジナル料理|
|Tagged and Bagged|狩りの収穫|猎获|クロリンデのオリジナル料理|
|Hearthfire's Trail|炉火の昔語り|炉火的往迹|召使のオリジナル料理|
|Yummy Yum Cha|飲茶しようぜ！|得闲饮茶|嘉明のオリジナル料理|
|Pick What You Like!|どれでもどーぞ！|选你喜欢的！|ナヴィアのオリジナル料理|
|Bulle Sauce Duck Breast|鴨胸肉のオレンジソースソテー|桔香鸭胸肉||フォンテーヌのレシピ|
|Consomme|コンソメスープ|百味一缕||フォンテーヌのレシピ|
|Rainbow Macarons|カラフルマカロン|缤纷马卡龙||フォンテーヌのレシピ|
|Honey Char Siu|蜜汁チャーシュー|蜜汁叉烧||璃月のレシピ|

Weapon
| English | Japanese | Chinese Simplifed | Note(ja) | type | memo |
|---|---|---|---|---|---|
| Silvershower Heartstrings | 白雨心弦 | 白雨心弦 || Bow | |

Domain
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Imaginarium Theater|幻想シアター|幻想真境剧诗||  |

Organization
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|The Liliacruces Ordo|鈴蘭十字結社|铃兰十字结社||必要? ペトリコール町のコンタリーニとの会話内の夢の話でしか出てこない

Event

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| Spino Doubleblaster |スプラッシュ・デュエット | 飞迸湍流二重奏 | Ver.4.7限定イベント||
| Endless Forms Most Martial |千変万化の豪傑譚 | 纷变繁相豪武谭 | Ver.4.7限定イベント||
| Record of Reflective Writing |ペンと空想の旅 | 绎思振笔集 | Ver.4.7限定イベント||
| Sprinting Stratagems | 奇策！スピード勝負 | 热斗模式: 奇策竞驰 | Ver.4.7限定イベント||

**Comment by yasuking0304** [comment]
Added/Modified

Domain
幻想シアター・1 → 幻想シアター

Books
小さな魔女と消えない炎、ニャンコ事務所

Characters in the "Imaginarium Theater" added to Mondstadt?
シノシシプリンセス(Already added in the book, add a tag with a character)、子オオカミ

New events
スプラッシュ・デュエット

**Comment by xicri** [comment]
Thanks and apologies for delayed response.

> シノシシプリンセス

Do you mean **イ**ノシシプリンセス or is it a new character in the Imaginarium Theater?
IIRC, シノシシプリンセス is not in the dictionary yet.

**Comment by yasuking0304** [comment]
Oops. It is a handwritten reprint error. I fixed the issue.
Ver.4.7 After merging the first part, we will issue a Pull Request for the second part.

**Comment by xicri** [comment]
Thanks.

I couldn't get drugs and was affected by a health problem in the last month, but because I got drugs today, (I hope) I will get well and work on the remaining PRs by the next weekend...

Thanks for your patience 🙏

**Comment by yasuking0304** [comment]
I don't need a sense of speed that makes me want newsworthiness, so it's okay.
Take care of yourself

**Comment by xicri** [comment]
@yasuking0304 Thanks for closing the Issues. I forgot to close them.

Just a tip: If you write `Closes #000` (Replace `000` with the Issue number) in the PR description, you can automatically close the Issue when the PR is merged.

https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
