### ISSUE TITLE
[References]Version 5.0 Preview Teaser

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#245]
Source of information
Japansese
https://www.youtube.com/watch?v=q__fo0CSEcE&ab_channel=%E5%8E%9F%E7%A5%9E-Genshin-%E5%85%AC%E5%BC%8F
Other(Change language English/中文 (简体))
https://www.youtube.com/watch?v=O2ATH__rtQo&t=3s&ab_channel=GenshinImpact

Charactor of Natlan

| English | Japanese | Chinese Simplifed | Note(ja) | Type | memo |
|---|---|---|---|---|---|
| Mualani | ムアラニ| 玛拉妮 || Unkown |
| Kachina |カチーナ| 卡齐娜|| Unkown |
| Kinich |キィニチ| 基尼奇 || Unkown |
| K'uhul Ajaw |クフル・アハウ| 库胡勒阿乔 || Unkown |
| Almighty Dragonlord (Self-Proclaimed) | 偉大なる聖龍（自称） |伟大圣龙（自称）| クフル・アハウの通称 | Unkown | tags:[how-to-call]
| Citlali |シトラリ| 茜特菈莉 || Unkown |
|Xilonen |シロネン| 希诺宁 || Unkown |
| 入力済み |イアンサ| - || Playable(Maybe)|
| Chasca |チャスカ|恰斯卡|| Unkown |
| Mavuika  |マーヴィカ| 玛薇卡 || Unkown |
| 入力済み | 隊長 | - || Unkown |
| Ororon |オロルン| 欧洛伦 || Unkown |

YouTube Comment (Official) Clipping.
![WS000021](https://github.com/user-attachments/assets/2f48c5ec-877f-4275-9ca9-fe4e0780de7e)
![WS000020](https://github.com/user-attachments/assets/8dc9c6c1-96c3-46b5-b560-f79f0b3d1dd9)
![WS000022](https://github.com/user-attachments/assets/ab484148-de8f-4222-81a6-890d4fcec43f)

**Comment by xicri** [comment]
Thanks, but unfortunately, I have already added these character names in #242 as I mentioned... 😣
