### ISSUE TITLE
CSVs include `[object Object]` in `備考` (`notes`) field

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#275]
## The problem
The download contents of the CSV file are wrong.

## Release version
Latest.

## Steps to reproduce the behavior
1.  Goto URL( https://genshin-dictionary.com/en/opendata )
2.  Click [CSV (UTF-8 版) をダウンロード](https://dataset.genshin-dictionary.com/words.csv) or [CSV (Shift_JIS 版) をダウンロード](https://dataset.genshin-dictionary.com/words-sjis.csv)
3. Open csv file.
4. The "備考" column is listed as [object object].

## Screen Shot
![WS000030](https://github.com/user-attachments/assets/76bf87eb-18d1-4f09-96a6-bb8f5e2dd287)

**Comment by xicri** [comment]
I found this bug is caused by a breaking change of `marked` v14.0.0.
I'm applying the fix soon.

A possible solution to prevent this kind of bug is migrating to TypeScript.

**Comment by xicri** [comment]
I have merged the fix, which will be deployed in a few minutes.
Thanks again for reporting!
