### ISSUE TITLE
Temporal update suspension due to my health problem

### ISSUE THREAD

**Issue by xicri** [xicri/genshin-langdata#282]
Dear contributors,

Due to my hospitalization, I may have to suspend updates for Genshin Dictionary for a while.
Please allow some weeks until I release your PRs. 🙏

cc: @yasuking0304

**Comment by yasuking0304** [comment]
Bless you. 5.0 Don't worry about updating the information. I'll just prepare it.

**Comment by xicri** [comment]
@yasuking0304 Thanks, I'm just came back home!
