### ISSUE TITLE
Add new keywords for Version 4.3 - 4.7 genshin-langdata

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#288]
Adds Fontaine's Story Quest, Domain, Drops and Artifact, we will add keywords(Additional omissions).

Archon Quest
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Bedtime Story | ベッドタイムストーリー | 睡前故事

Sub Story Title(Event)
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| An Everlasting Dream Intertwined | 永き夢を紡いで | 纺坠终久之梦 | | v4.7
| Two Worlds Aflame, the Crimson Night Fades | 双界に至る炎、熄えゆく赤夜 | 两界为火，赤夜将熄 | | v4.6
| Blades Weaving Betwixt Brocade | 鋒刃、錦を裁つ | 铓锋锦间裁 | | v4.5
| Vibrant Harriers Aloft in Spring Breeze | 彩る紙鳶、春梳きて | 彩鹞栉春风 | | v4.4
| Roses and Muskets | 薔薇と騎士 | 蔷薇与铳枪 | | v4.3

Story Quest
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Diluvies Capture | 潮汐の章 | 潮涌之章 | ヌヴィレットの伝説任務| add tags:[fontaine]
|入力済み| 頌歌者の章 | | フリーナの伝説任務
| Rosa Multiflora Capture | 野薔薇の章 | 野蔷薇之章 | ナヴィアの伝説任務| add tags:[fontaine]
| Grus Serena Capture | 閑鶴の章 | 闲鹤之章 | 閑雲の伝説任務| add tags:[liyue]
| Cisoria Capture | 糸切鋏の章 | 丝切铗之章 | 千織の伝説任務| add tags:[fontaine]
| Ignis Purgatorius Capture | 浄煉の炎の章 | 净炼火之章 | アルレッキーノの伝説任務| add tags:[fontaine]
| Rappiera Chapter | レイピアの章 | 迅捷剑之章 | クロリンデの伝説任務 | add tags:[fontaine]
| Nereides Capture | ネレイスの章 | 海精之章 | シグウィンの伝説任務| add tags:[fontaine]
| Ponum de Ambra Capture | ポムム・ドゥ・アンブラの章 | 香氛瓶之章 | エミリエの伝説任務 | add tags:[sumeru]

Domain of fontaine
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| Waterfall Wen | 滝を臨む廃都 | 临瀑之城 || | 
| Faded Theater | 色褪せた劇場 | 褪色的剧场 || | 
| Scattered Ruins | ぼろぼろの廃墟 | 零落丘墟 || |

Boss Drops in fontaine
| English | Japanese | Chinese Simplifed | Note(ja) | memo|
|---|---|---|---|---|
| Fading Candle | 残火の灯燭 | 残火灯烛
| Silken Feather | 絹織りの羽 | 丝织之羽
| Denial and Judgment | 否定と裁決 | 否定裁断

Artifact in fontaine
| English | Japanese | Chinese Simplifed | Note(ja) | memo|
|---|---|---|---|---|
| Song of Days Past | 在りし日の歌 | 昔时之歌
| Nighttime Whispers in the Echoing Woods | 残暑の森で囁かれる夜話 | 回声之林夜话
| Fragment of Harmonic Whimsy | 諧律奇想の断章 | 谐律异想断章
| Unfinished Reverie | 遂げられなかった想い | 未竟的遐思

A Piece of Artifacts in fontaine
| English | Japanese | Chinese Simplifed | Note(ja) | memo|
|---|---|---|---|---|
| Forgotten Oath of Days Past | 在りし日の遺失の契 | 昔时遗落之誓 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Recollection of Days Past | 在りし日の空想の念 | 昔时浮想之思 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Echoing Sound From Days Past | 在りし日の余韻の音 | 昔时回映之音 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Promised Dream of Days Past | 在りし日の約束の夢 | 昔时应许之梦 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Poetry of Days Past | 在りし日の伝奏の詩 | 昔时传奏之诗 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Selfless Floral Accessory | 無私の花飾り | 无私的妆饰花 | 聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Honest Quill | 誠実なつけペン | 诚恳的蘸水笔 | 聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Faithful Hourglass | 忠実な砂時計 | 忠实的砂时计 | 聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Magnanimous Ink Bottle | 寛容なインク壺 | 慷慨的墨水瓶 | 聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Compassionate Ladies' Hat | 慈愛の淑女ハット | 慈爱的淑女帽 |聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Harmonious Symphony Prelude | 響き合う諧律の前奏 | 谐律交响的前奏 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| Ancient Sea's Nocturnal Musing | 古海の幽深なる夜想 | 古海玄幽的夜想 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| The Grand Jape of the Turning of Fate | 運命と輪廻の諧謔 | 命途轮转的谐谑 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| Ichor Shower Rhapsody | 降り注ぐイコルの狂詩 |灵露倾洒的狂诗 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| Whimsical Dance of the Withered | 異想が枯れ落ちる円舞 | 异想零落的圆舞 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| Dark Fruit of Bright Flowers | 陰に咲く光の花 | 暗结的明花 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
| Faded Emerald Tail | 光褪せた翠尾 | 褪光的翠尾 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
| Moment of Attainment | 大業を成す刻 | 举业的识刻 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
| The Wine-Flask Over Which the Plan Was Hatched | 計略の盃 | 筹谋的共樽 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
| Crownless Crown | 主なき冠 | 失冕的宝冠 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |

Serenitea Pot
| English | Japanese | Chinese Simplifed | Note(ja) | memo|
|---|---|---|---|---|
| Ash Wood | ホワイトアッシュ材 | 白梣木 |

**Comment by xicri** [comment]
Thanks! Please send me a PR!

A few comments:

- I guess the Story Quest names should end with **Chapter** (章), not **Capture** (捕まえる). (e.g. Diluvies ~~Capture~~ Chapter)
- I have stopped to add the pieces of artifacts because I guess the users don't need them. You can add them if you wish, but you still have an option not to add them.

**Comment by yasuking0304** [comment]
* Capture → Chapter
* delete "A Piece of Artifacts in fontaine"

A Piece of Artifacts in fontaine

| English | Japanese | Chinese Simplifed | Note(ja) | memo|
|---|---|---|---|---|
| Forgotten Oath of Days Past | 在りし日の遺失の契 | 昔时遗落之誓 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Recollection of Days Past | 在りし日の空想の念 | 昔时浮想之思 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Echoing Sound From Days Past | 在りし日の余韻の音 | 昔时回映之音 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Promised Dream of Days Past | 在りし日の約束の夢 | 昔时应许之梦 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Poetry of Days Past | 在りし日の伝奏の詩 | 昔时传奏之诗 | 聖遺物セット「在りし日の歌」（Song of Days Past）の1つ| |
| Selfless Floral Accessory | 無私の花飾り | 无私的妆饰花 | 聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Honest Quill | 誠実なつけペン | 诚恳的蘸水笔 | 聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Faithful Hourglass | 忠実な砂時計 | 忠实的砂时计 | 聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Magnanimous Ink Bottle | 寛容なインク壺 | 慷慨的墨水瓶 | 聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Compassionate Ladies' Hat | 慈愛の淑女ハット | 慈爱的淑女帽 |聖遺物セット「残暑の森で囁かれる夜話」（Nighttime Whispers in the Echoing Woods）の1つ| |
| Harmonious Symphony Prelude | 響き合う諧律の前奏 | 谐律交响的前奏 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| Ancient Sea's Nocturnal Musing | 古海の幽深なる夜想 | 古海玄幽的夜想 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| The Grand Jape of the Turning of Fate | 運命と輪廻の諧謔 | 命途轮转的谐谑 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| Ichor Shower Rhapsody | 降り注ぐイコルの狂詩 |灵露倾洒的狂诗 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| Whimsical Dance of the Withered | 異想が枯れ落ちる円舞 | 异想零落的圆舞 | 聖遺物セット「諧律奇想の断章」（Fragment of Harmonic Whimsy）の1つ| |
| Dark Fruit of Bright Flowers | 陰に咲く光の花 | 暗结的明花 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
| Faded Emerald Tail | 光褪せた翠尾 | 褪光的翠尾 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
| Moment of Attainment | 大業を成す刻 | 举业的识刻 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
| The Wine-Flask Over Which the Plan Was Hatched | 計略の盃 | 筹谋的共樽 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
| Crownless Crown | 主なき冠 | 失冕的宝冠 | 聖遺物セット「遂げられなかった想い」（Unfinished Reverie）の1つ| |
