### ISSUE TITLE
Add/Update new keywords for Version 5.0 sequel genshin-langdata

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#301]
Since we have advanced the story of the 2nd half of Ver 5.0, we will add keywords. This time, I am creating it from Genshin Impact's "Archive" - "Travel Log", item and movie.
And sorry, I found a lot of typos and will fix them.

Write in tags.json of Natlan
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | memo |
|---|---|---|---|---|---|---|
| Tribal Chronicles | 部族見聞 | 部族纪闻 | Chinese & Japanese translations for the Tribal Chronicles in Genshin Impact | 原神の部族見聞の英語・中国語表記一覧 | 原神中的部族纪闻的英语和日语翻译 | 追加の必要性を踏まえて要検討

Quest (Tribal Chronicles)
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | memo | 
|---|---|---|---|---|---|---|
| Where the Springs Return | 流泉の帰す場所(りゅうせんのかえすばしょ) | 流泉所归之处 | Tribal Chronicles, Natlan | ナタの部族見聞 | 纳塔的部族纪闻 | 【検討】add tags:[tribal-chronicles] 
| Yupanqui's Turnfire | ユパンキの廻焔(ユパンキのかいえん) | 尤潘基的回火 | Tribal Chronicles, Natlan | ナタの部族見聞| 纳塔的部族纪闻| 【検討】add tags:[tribal-chronicles]
| A Prayer for Blessings, Told to Crested Peaks | 祝福を祈り、テペトルに告ぐ(しゅくふくをいのりテペトルにつぐ) | 祈祝福愿，倾告嵴锋 | Tribal Chronicles, Natlan  | ナタの部族見聞 | 纳塔的部族纪闻 | 【検討】add tags:[tribal-chronicles]

Write in system.json5 of Natlan
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| TurnFire | 廻焔 | 回火

Events
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
|  | いばらと栄冠 | | | not yet

Daily Quest
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Hmm? Natlan? | えっ？ナタ？ | 咦？纳塔？
| Sharpshooter on Hand | 手に妙影 | 妙影在手

Books (Item)
| English | Japanese | Chinese Simplifed | Note(ja) | memo|
|---|---|---|---|---|
| Maawe and Monetto | マーウェと幻写霊 | 玛阿威与幻写灵
| The Page Princess and the Six Pygmies | 白姫と六人の小人(しらひめとろくにんのこびと) | 白之公主与六侏儒

Weapon 
| English | Japanese | Chinese Simplifed | Note(ja) | Type |memo|
|---|---|---|---|---|---|
| Fang of the Mountain King | 山の王の長牙 | 山王长牙 || Claymore

Charactor of Natlan
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zn-ch) |Type | memo|
|---|---|---|---|---|---|---|---|
| Pacal | パカル | 帕加尔 | Chief, Children of Echoes |「こだまの子」族長 | 「回声之子」首领 | NPC
| Wayna | ワイナ | 瓦伊纳 | Chief, Scions of the Canopy | 「懸木の民」族長 | 「悬木人」首领 | NPC
| Amina | アミナ | 阿米娜 | Chief, People of the Springs | 「流泉の衆」族長 | 「流泉之众」首领 | NPC | Sorry, I forgot to enter it in the last PR.
| 入力済み | フニ | || 部族見聞「ユパンキの廻焔」に登場する人物 | | NPC |  Sorry. fixed typo 「ユバンキ」→「ユパンキ」|
| 入力済み | トバ | || 部族見聞「ユパンキの廻焔」に登場する人物 | | NPC | Sorry. fixed typo 「ユバンキ」→「ユパンキ」 |
| 入力済み| 山下 | || 部族見聞「ユパンキの廻焔」に登場するアビス教団の使者 || NPC | Sorry. fixed typo 「ユバンキ」→「ユパンキ」 
| 入力済み | トリニダード | || 部族見聞「ユバンキの廻焔」に登場する人物 | | NPC | Sorry. fixed typo 「ユバンキ」→「ユパンキ」 |
| Thiago | ティアゴ | 蒂亚戈 || 部族見聞「ユパンキの廻焔」第三幕に登場する人物 || NPC | 
| Ponche | ポンセ | 庞塞 || 部族見聞「ユパンキの廻焔」第三幕に登場する人物 || NPC |
| Matthias | マティアス | 马蒂亚斯 || 部族見聞「ユパンキの廻焔」第三幕に登場する人物 || NPC | 必要?
| Burkina | ブルキナ | 布基纳 || 部族見聞「ユパンキの廻焔」に登場する人物 || NPC
| Kongamato | コンガマトー | 康加玛托 || 部族見聞「ユパンキの廻焔」に登場する巨大なユムカ竜 || NPC | 
| Mountain King | 山の王 | 山王 || コンガマトーの敬称 || NPC | add tags:[how-to-call] 
| Ponini | ポニニ | 波尼尼 || 部族見聞「ユパンキの廻焔」に登場するユムカ竜 || NPC
| Poggi | ポギギ | 波吉吉 || 部族見聞「ユパンキの廻焔」に登場するユムカ竜 || NPC
| Pocchi | ポチチ | 波奇奇 || 部族見聞「ユパンキの廻焔」に登場するユムカ竜 || NPC
| Nanna | ナンナ | 南娜 || 部族見聞「ユパンキの廻焔」に登場するユムカ竜 || NPC

Food
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zn-ch) | memo |
|---|---|---|---|---|---|---|
| Saurian Hunter's Reward | 竜狩り人の褒賞 | 猎龙者的犒赏 | Kinich's specialty | キィニチのオリジナル料理 | 基尼奇的特色料理

**Comment by xicri** [comment]
Thanks as always!
Here's my ideas for this Issue:

- I have suggestions for the tag for Tribal Chronicles
  - I want to make tag ID `quest-tribal` so that it starts with `quest-` prefix as well as other quest tags
  - I want to make English tag name "Tribal Chronicle" because other tag names are singular.
- Can you also add Tribal Chronicle as a word?
- If you add `quest-tribal` tag, I think the notes for each tribal chronicle "Tribal Chronicles, Natlan" are duplicate. Since the tags explains what the words are, the notes can be removed IMO.

**Comment by yasuking0304** [comment]
Thank you for your review.
I accepted your suggestion and made the following changes.
I will now submit a PR.

Write in tags.json of Natlan
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | memo |
|---|---|---|---|---|---|---|
| Tribal Chronicles | 部族見聞 | 部族纪闻 | Chinese & Japanese translations for the Tribal Chronicles in Genshin Impact | 原神の部族見聞の英語・中国語表記一覧 | 原神中的部族纪闻的英语和日语翻译 | key name: quest-tribal

Quest (Tribal Chronicles)
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | memo | 
|---|---|---|---|---|---|---|
| Tribal Chronicles | 部族見聞(ぶぞくけんぶん) | 部族纪闻 |||| add tags:[quest-tribal] 

Quest (Tribal Chronicles) of Natlan
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | memo | 
|---|---|---|---|---|---|---|
| Where the Springs Return | 流泉の帰す場所(りゅうせんのかえすばしょ) | 流泉所归之处 | | | | add tags:[quest-tribal] 
| Yupanqui's Turnfire | ユパンキの廻焔(ユパンキのかいえん) | 尤潘基的回火 | | | | add tags:[quest-tribal]
| A Prayer for Blessings, Told to Crested Peaks | 祝福を祈り、テペトルに告ぐ(しゅくふくをいのりテペトルにつぐ) | 祈祝福愿，倾告嵴锋 |||| add tags:[quest-tribal]

Write in system.json5 of Natlan
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| TurnFire | 廻焔 | 回火


Events
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Of Thorns and Crowns | いばらと栄冠 | 荆棘与勋冠 | v5.0 期間限定イベント | 

Daily Quest
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Hmm? Natlan? | えっ？ナタ？ | 咦？纳塔？
| Sharpshooter on Hand | 手に妙影 | 妙影在手
| Prophets of Pop | 流行りの音楽 | 流行音乐，谁先知？

Books (Item)
| English | Japanese | Chinese Simplifed | Note(ja) | memo|
|---|---|---|---|---|
| Maawe and Monetto | マーウェと幻写霊 | 玛阿威与幻写灵
| The Page Princess and the Six Pygmies | 白姫と六人の小人(しらひめとろくにんのこびと) | 白之公主与六侏儒


Weapon 
| English | Japanese | Chinese Simplifed | Note(ja) | Type |memo|
|---|---|---|---|---|---|
| Fang of the Mountain King | 山の王の長牙 | 山王长牙 || Claymore

Charactor of Natlan
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zn-ch) |Type | memo|
|---|---|---|---|---|---|---|---|
| Pacal | パカル | 帕加尔 | Chief, Children of Echoes |「こだまの子」族長 | 「回声之子」首领 | NPC
| Wayna | ワイナ | 瓦伊纳 | Chief, Scions of the Canopy | 「懸木の民」族長 | 「悬木人」首领 | NPC
| Amina | アミナ | 阿米娜 | Chief, People of the Springs | 「流泉の衆」族長 | 「流泉之众」首领 | NPC | Sorry, I forgot to enter it in the last PR.
| 入力済み | フニ | || 部族見聞「ユパンキの廻焔」に登場する人物 | | NPC |  Sorry. fixed typo 「ユバンキ」→「ユパンキ」|
| 入力済み | トバ | || 部族見聞「ユパンキの廻焔」に登場する人物 | | NPC | Sorry. fixed typo 「ユバンキ」→「ユパンキ」 |
| 入力済み| 山下 | || 部族見聞「ユパンキの廻焔」に登場するアビス教団の使者 || NPC | Sorry. fixed typo 「ユバンキ」→「ユパンキ」 
| 入力済み | トリニダード | || 部族見聞「ユバンキの廻焔」に登場する人物 | | NPC | Sorry. fixed typo 「ユバンキ」→「ユパンキ」 |
| Thiago | ティアゴ | 蒂亚戈 || 部族見聞「ユパンキの廻焔」第三幕に登場する人物 || NPC | 
| Ponche | ポンセ | 庞塞 || 部族見聞「ユパンキの廻焔」第三幕に登場する人物 || NPC |
| Matthias | マティアス | 马蒂亚斯 || 部族見聞「ユパンキの廻焔」第三幕に登場する人物 || NPC | 必要?
| Burkina | ブルキナ | 布基纳 || 部族見聞「ユパンキの廻焔」に登場する人物 || NPC
| Kongamato | コンガマトー | 康加玛托 || 部族見聞「ユパンキの廻焔」に登場する巨大なユムカ竜 || NPC | 
| Mountain King | 山の王 | 山王 || コンガマトーの敬称 || NPC | add tags:[how-to-call] 
| Ponini | ポニニ | 波尼尼 || 部族見聞「ユパンキの廻焔」に登場するユムカ竜 || NPC
| Poggi | ポギギ | 波吉吉 || 部族見聞「ユパンキの廻焔」に登場するユムカ竜 || NPC
| Pocchi | ポチチ | 波奇奇 || 部族見聞「ユパンキの廻焔」に登場するユムカ竜 || NPC
| Nanna | ナンナ | 南娜 || 部族見聞「ユパンキの廻焔」に登場するユムカ竜 || NPC

Food
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zn-ch) | memo |
|---|---|---|---|---|---|---|
| Saurian Hunter's Reward | 竜狩り人の褒賞 | 猎龙者的犒赏 | Kinich's specialty | キィニチのオリジナル料理 | 基尼奇的特色料理
