### ISSUE TITLE
Add new keywords for September, 2024 genshin-langdata

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#310]
Since we have advanced the story, we will add keywords. This time, I am creating it from Genshin Impact's "Archive" - "Travel Log", item, voice and movie.

Events
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Of Thorns and Crowns | いばらと栄冠 | 荆棘与勋冠 | v5.0 期間限定イベント | 

Daily Quest
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Daydream Club: Thermal Hypnosis | 空想クラブ・熱エネルギー睡眠導入 | 空想俱乐部・热能催眠
| Grow Up Quickly, Littl'Un | はやく大きくなーれ！ | 小小人儿，快长大
| Grow Up Quickly, Littl'Un...? | はやく大きくなーれ…？ | 小小人儿，快长大…？ | | 「...」について、英語はドット3つ、他の言語は三点リーダー記号

World Quest of Sumeru
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja)  | Note(zh-cn) | memo |
|---|---|---|---|---|---|---|
| The Path of Papers | 学を求む長き道 | 求学漫漫路 |  | 

Object (English and Simplified Chinese are temporary)
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) | memo|
|---|---|---|---|---|---|---|
| 入力済み | 邪眼 | | | | | add tag:[object, fatui]<br>邪眼に関しては謎が多いので説明は特に付与していません
| 入力済み | ウサギ伯爵 |  | Amber's homemade rabbit bomb doll | アンバー自作のウサギ型爆弾人形 | 安柏自己的兔子形炸弹玩偶 | add tag:[object]
| 入力済み | ドドコ |  | The doll was made by Klee's mother, Alice, and named by Klee | クレーの母親のアリスが作り、クレーが名付けた人形 | 这个玩偶是可莉的妈妈艾莉丝制作的，并由可莉命名 | add tag:[object]
| 入力済み | ボンボン爆弾 |  | A dodoco-type bomb doll created by Klee's elemental skills | クレーが元素スキルで生成する、ドドコ型爆弾人形 | 可莉通过元素战技制造出的嘟嘟可形状的炸弹玩偶 | add tag:[object]
| Ice Lotus | 氷蓮(ひょうれん) | 冰莲 | A lotus-like ice bomb created by Ganyu's elemental skills | 甘雨が元素スキルで生成する、蓮の形をした氷元素爆弾 | 甘雨元素战技制造出来的莲花状冰的炸弹 | add tag:[object] 
| 入力済み | コレアンバー |  | Collei's homemade cat-shaped bomb doll | コレイ自作のネコ型爆弾人形 | 柯莱自制的猫形炸弹玩偶 | add tag:[object]
| 入力済み | ニャルダモン |  | A cat-shaped dendro bomb created by Kirara's elemental burst | 綺良々が元素爆発で生成する、ネコ型の草元素爆弾　| 绮良良通过元素爆炸制造出的猫形草元素炸弹 | add tag:[object]
| Monsieur Verite | ヴェリテくん | 溫亨廷先生 | Charlotte's favorite camera | シャルロット愛用のカメラ | 夏洛蒂最喜欢的相机 | add tag:[fontaine]
| Grin-Malkin Hat | ファニーキャット・ハット | 怪笑猫猫帽| A cat-shaped hat used by Lyney in her elemental skills |リネが元素スキルで取り出す、ネコ型帽子 | 林尼用元素战技取出的猫形帽子  | add tag:[fontaine]
| Bogglecat Box | ビックラキャット・ボックス | 惊奇猫猫盒 | A cat-shaped box used by Lynette in her elemental bursts | リネットが元素爆発で取り出す、ネコ型ボックス  | 琳妮特在元素爆发中使用的猫形盒 | add tag:[fontaine]
| | | | | | | |
| 入力済み | ネコ箱急便 | | Kirara transforms with her elemental skill into a cat in a cardboard box | 綺良々が元素スキルで変身する、ダンボールのような箱に入ったネコの状態 | 绮良良因元素技能变成了一只装在纸板箱里的猫 | Is this an object?  or playable character?
| Grin-Malkin Cat | ファニーハット・キャット | 怪笑帽帽猫 | Lyney transforms with elemental burst into a hat-shaped cat(Not a "Grin-Malkin Hat") | リネが元素爆発で変身する、帽子型ネコの状態(ファニーキャット・ハットではない) | 林尼因元素爆爆变成了为帽子形状的猫(井不是「怪笑猫猫帽」) | add tag:[fontaine] <br>Is this an object?  or playable character?

Character (English and Simplified Chinese are temporary)
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) |Type | memo|
|---|---|---|---|---|---|---|---|
| 入力済み | アラニ | | Character appearing in many world quests, including ”And This Treasure Goes To...”, "The Path of Papers" | 「霊矩のお宝」「学を求む長き道」など、多くの世界任務に登場する人物 | 出现在「灵矩有宝予何人」，「求学漫漫路」等众多世界任务中的角色 |  NPC | add tag:[liyue, natlan]
| Narzam | ナザム | 娜赞 | Character appearing in the world quest "The Path of Papers" | 世界任務「学を求む長き道」に登場する人物  | 世界任务「求学漫漫路」中出现的角色 | NPC | add tag:[sumeru, natlan]
| Ifa | イファ | 伊法 | Saurian vet from the "Flower-Feather Clan" | 「花翼の集」の竜医 | 「花羽会」中的龙医 | Playable? | add tag:[natlan]<br>ムアラニ/カチーナ/キィニチのボイスでのみ出てくる人物

Location
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| "Flower-Feather Clan" | 「花翼の集」 | 「花羽会」　|| add tags:[Organization] |

**Comment by xicri** [comment]
Thanks as always!

Here's my ideas for your plan:

- `object` tag means field object, so I want to avoid tagging `object` to Delusion (邪眼).
  - cf. [A definition of "object" in RPG Maker (RPG ツクール)](https://rpgmakerofficial.com/product/act/manual/06_01.html). According to this definition, "object" includes characters and enemies, but I only call non-living things "object" in the Dictionary.
- For the objects generated by characters skills such as Baron bunny and Grin-Malkin Hat, I'm wondering if we should create new tag "Battle Skills" (戦闘スキル) tag. By creating this tag, users can aggregate the character skill-related words including Xiangling's Guoba, who should not be tagged `object`. However, too detailed tagging might cause confusion by the users and the developers like you and me. Can you let me know your opinion?
- Alrani (アラニ) is from Sumeru and she appears in a world quest in Sumeru too, so I guess `sumeru` tag is also required.
- For Ifa, let's add `character-sub` tag until we can confirm that s/he will be a playable character.

**Comment by yasuking0304** [comment]
Okay, so why not just add each element to tag.json instead?

Write in tags.json
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | memo |
|---|---|---|---|---|---|---|
| Anemo | 風 |  风 | Chinese & Japanese translations for words related to Anemo(Wind) |  風に関する言葉の英語・中国語表記一覧 | 原神中的风相关的英语和日语翻译 | key name: anemo
| Geo | 岩 | 岩 | Chinese & Japanese translations for words related to Geo(Rock) | 岩に関する言葉の英語・中国語表記一覧 | 原神中的岩相关的英语和日语翻译 | key name: geo
| Electro | 雷 | 雷 |  Chinese & Japanese translations for words related to Electro(Thunder) | 雷に関する言葉の英語・中国語表記一覧 | 原神中的雷相关的英语和日语翻译 | key name: electro
| Dendro | 草 | 草 | Chinese & Japanese translations for words related to Dendro(Grass) | 草に関する言葉の英語・中国語表記一覧 | 原神中的草相关的英语和日语翻译 | key name: dendro
| Hydro | 水 | 水 | Chinese & Japanese translations for words related to Hydro(Water) | 水に関する言葉の英語・中国語表記一覧 |  原神中的水相关的英语和日语翻译 | key name: hydro
| Pyro | 炎 | 火 | Chinese & Japanese translations for words related to Pyro(Fire) | 炎に関する言葉の英語・中国語表記一覧 |  原神中的火相关的英语和日语翻译 | key name: pyro
| Cryo | 氷 | 冰 | Chinese & Japanese translations for words related to Cryo(Ice) | 氷に関する言葉の英語・中国語表記一覧 | 原神中的冰相关的英语和日语翻译 | key name: cryo

**Comment by yasuking0304** [comment]
After the correction, it will look like this.

Write in tags.json
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | memo |
|---|---|---|---|---|---|---|
| Anemo | 風 |  风 | Chinese & Japanese translations for words related to Anemo(Wind) |  風に関する言葉の英語・中国語表記一覧 | 原神中的风相关的英语和日语翻译 | key name: anemo
| Geo | 岩 | 岩 | Chinese & Japanese translations for words related to Geo(Rock) | 岩に関する言葉の英語・中国語表記一覧 | 原神中的岩相关的英语和日语翻译 | key name: geo
| Electro | 雷 | 雷 |  Chinese & Japanese translations for words related to Electro(Thunder) | 雷に関する言葉の英語・中国語表記一覧 | 原神中的雷相关的英语和日语翻译 | key name: electro
| Dendro | 草 | 草 | Chinese & Japanese translations for words related to Dendro(Grass) | 草に関する言葉の英語・中国語表記一覧 | 原神中的草相关的英语和日语翻译 | key name: dendro
| Hydro | 水 | 水 | Chinese & Japanese translations for words related to Hydro(Water) | 水に関する言葉の英語・中国語表記一覧 |  原神中的水相关的英语和日语翻译 | key name: hydro
| Pyro | 炎 | 火 | Chinese & Japanese translations for words related to Pyro(Fire) | 炎に関する言葉の英語・中国語表記一覧 |  原神中的火相关的英语和日语翻译 | key name: pyro
| Cryo | 氷 | 冰 | Chinese & Japanese translations for words related to Cryo(Ice) | 氷に関する言葉の英語・中国語表記一覧 | 原神中的冰相关的英语和日语翻译 | key name: cryo

Events
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Of Thorns and Crowns | いばらと栄冠 | 荆棘与勋冠 | v5.0 期間限定イベント | 

Daily Quest
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Daydream Club: Thermal Hypnosis | 空想クラブ・熱エネルギー睡眠導入 | 空想俱乐部・热能催眠
| Grow Up Quickly, Littl'Un | はやく大きくなーれ！ | 小小人儿，快长大
| Grow Up Quickly, Littl'Un...? | はやく大きくなーれ…？ | 小小人儿，快长大…？ | | 「...」について、英語はドット3つ、他の言語は三点リーダー記号

World Quest of Sumeru
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja)  | Note(zh-cn) | memo |
|---|---|---|---|---|---|---|
| The Path of Papers | 学を求む長き道 | 求学漫漫路 |  | 

Character (English and Simplified Chinese are temporary)
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) |Type | memo|
|---|---|---|---|---|---|---|---|
| 入力済み | アラニ | | Character appearing in many world quests, including ”And This Treasure Goes To...”, "The Path of Papers" | 「霊矩のお宝」「学を求む長き道」など、多くの世界任務に登場する人物 | 出现在「灵矩有宝予何人」，「求学漫漫路」等众多世界任务中的角色 |  NPC | add tag:[liyue, sumeru, natlan]
| Narzam | ナザム | 娜赞 | Character appearing in the world quest "The Path of Papers" | 世界任務「学を求む長き道」に登場する人物  | 世界任务「求学漫漫路」中出现的角色 | NPC | add tag:[sumeru, natlan]
| Ifa | イファ | 伊法 | Saurian vet from the "Flower-Feather Clan" | 「花翼の集」の竜医 | 「花羽会」中的龙医 | NPC | add tag:[natlan]<br>ムアラニ/カチーナ/キィニチのボイスでのみ出てくる人物

Location
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| "Flower-Feather Clan" | 「花翼の集」 | 「花羽会」　|| add tags:[Organization] |

Else (English and Simplified Chinese are temporary)
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) | memo|
|---|---|---|---|---|---|---|
| 入力済み | 邪眼 | | | | | add tag:[fatui]
| 入力済み | ウサギ伯爵 |  | Amber's homemade rabbit bomb doll | アンバー自作のウサギ型爆弾人形 | 安柏自己的兔子形炸弹玩偶 | add tag:[object, pyro]
| 入力済み | ドドコ |  | The doll was made by Klee's mother, Alice, and named by Klee | クレーの母親のアリスが作り、クレーが名付けた人形 | 这个玩偶是可莉的妈妈艾莉丝制作的，并由可莉命名 | add tag:[object]
| 入力済み | ボンボン爆弾 |  | A dodoco-type bomb doll created by Klee's elemental skills | クレーが元素スキルで生成する、ドドコ型爆弾人形 | 可莉通过元素战技制造出的嘟嘟可形状的炸弹玩偶 | add tag:[pyro]
| Ice Lotus | 氷蓮(ひょうれん) | 冰莲 | A lotus-like ice bomb created by Ganyu's elemental skills | 甘雨が元素スキルで生成する、蓮の形をした氷元素爆弾 | 甘雨元素战技制造出来的莲花状冰的炸弹 | add tag:[cryo] 
| 入力済み | コレアンバー |  | Collei's homemade cat-shaped bomb doll | コレイ自作のネコ型爆弾人形 | 柯莱自制的猫形炸弹玩偶 | add tag:[object, dendro]
| 入力済み | ニャルダモン |  | A cat-shaped dendro bomb created by Kirara's elemental burst | 綺良々が元素爆発で生成する、ネコ型の草元素爆弾　| 绮良良通过元素爆炸制造出的猫形草元素炸弹 | add tag:[dendro]
| Monsieur Verite | ヴェリテくん | 溫亨廷先生 | Charlotte's favorite camera | シャルロット愛用のカメラ | 夏洛蒂最喜欢的相机 | add tag:[object]
| Grin-Malkin Hat | ファニーキャット・ハット | 怪笑猫猫帽| A cat-shaped hat used by Lyney in her elemental skills |リネが元素スキルで取り出す、ネコ型帽子 | 林尼用元素战技取出的猫形帽子  | add tag:[pyro]
| Bogglecat Box | ビックラキャット・ボックス | 惊奇猫猫盒 | A cat-shaped box used by Lynette in her elemental bursts | リネットが元素爆発で取り出す、ネコ型ボックス  | 琳妮特在元素爆发中使用的猫形盒 | add tag:[anemo]
| 入力済み | ネコ箱急便 | | Kirara transforms with her elemental skill into a cat in a cardboard box | 綺良々が元素スキルで変身する、ダンボールのような箱に入ったネコの状態 | 绮良良因元素技能变成了一只装在纸板箱里的猫 | add tag:[dendro]
| Grin-Malkin Cat | ファニーハット・キャット | 怪笑帽帽猫 | Lyney transforms with elemental burst into a hat-shaped cat(Not a "Grin-Malkin Hat") | リネが元素爆発で変身する、帽子型ネコの状態(ファニーキャット・ハットではない) | 林尼因元素爆爆变成了为帽子形状的猫(井不是「怪笑猫猫帽」) | add tag:[pyro]

**Comment by yasuking0304** [comment]
We will be adding element tags to main-character as well in the near future.

**Comment by yasuking0304** [comment]
I thought about it for a day, but I decided that I should separate the elements from this proposal. This time, I would like to create a PR with just the following content.

Events
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Of Thorns and Crowns | いばらと栄冠 | 荆棘与勋冠 | v5.0 期間限定イベント | 
| Mementos of Teyvat  | テイワットの思い出 | 提瓦特忆画 | v5.0 期間限定イベント | 
| Paimon's Kamera | パイモンの写真機 | 派蒙的留影机 | v5.0 期間限定イベント「テイワットの思い出」内で使える写真機 | add tag[item]

Daily Quest
| English | Japanese | Chinese Simplifed | Note(ja)  | memo|
|---|---|---|---|---|
| Daydream Club: Thermal Hypnosis | 空想クラブ・熱エネルギー睡眠導入 | 空想俱乐部・热能催眠
| Grow Up Quickly, Littl'Un | はやく大きくなーれ！ | 小小人儿，快长大
| Grow Up Quickly, Littl'Un...? | はやく大きくなーれ…？ | 小小人儿，快长大…？ | | 「...」について、英語はドット3つ、他の言語は三点リーダー記号

World Quest
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja)  | Note(zh-cn) | memo |
|---|---|---|---|---|---|---|
| The Path of Papers | 学を求む長き道 | 求学漫漫路 | add tag:[sumeru] | 
| A Honest Promotion | 良心的なキャンペーン | 善良促销

Character (English and Simplified Chinese are temporary)
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) |Type | memo|
|---|---|---|---|---|---|---|---|
| 入力済み | アラニ | | Character appearing in many world quests, including ”And This Treasure Goes To...”, "The Path of Papers" | 「霊矩のお宝」「学を求む長き道」など、多くの世界任務に登場する人物 | 出现在「灵矩有宝予何人」，「求学漫漫路」等众多世界任务中的角色 |  NPC | add tag:[liyue, sumeru, natlan]
| Narzam | ナザム | 娜赞 | Character appearing in the world quest "The Path of Papers" | 世界任務「学を求む長き道」に登場する人物  | 世界任务「求学漫漫路」中出现的角色 | NPC | add tag:[sumeru, natlan]
| Ifa | イファ | 伊法 | Saurian vet from the "Flower-Feather Clan" | 「花翼の集」の竜医。タグのプレイアブル・NPC 分類は仮 | 「花羽会」中的龙医 | NPC | add tag:[natlan]<br>ムアラニ/カチーナ/キィニチのボイスでのみ出てくる人物

Item
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| Firstborn Firesprite | 新生の霊炎 | 初诞灵焰 ||  |

Location
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| "Flower-Feather Clan" | 「花翼の集」 | 「花羽会」　|| add tags:[Organization] |

**Comment by xicri** [comment]
Element tags sounds nice. It should be useful for users to filter characters (and possibly enemies and so on?) by their element.

However, I don't think it solves the problem of the confusion for the tagging to the skill-related words.

Anyway, let's keep the tags as is at this time and consider how to resolve this issue later.
