### ISSUE TITLE
Add keywords for October, 2024 genshin-langdata

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#323]
Since we have advanced the story, we will add keywords. This time, I am creating it from Genshin Impact's "Archive" - "Travel Log", item, voice, movie.
We have also enhanced the English and simplified Chinese comments about gods and adeptus.

Events
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(Zh) | memo|
|---|---|---|---|---|---|---|
| 入力済み | 追憶練行(ついおくれんぎょう) | | Limited Time Event in v2.8 | | v2.8中的限时活动 | ふりがな追加
| 入力済み | いばらと栄冠 | | Limited Time Event in v5.0 | | v5.0中的限时活动 | 
| 入力済み | 巡れ！ワンダフルグラフィティ | | Limited Time Event in v5.0 | | v5.0中的限时活动 | 
| 入力済み | テイワットの思い出 | | Limited Time Event to celebrate the Fourth Anniversary | | 四周年纪念的限时活动 | 
| 入力済み | ドドコバンバン冒険記 | | Limited Time Event in v5.0 | | v5.0中的限时活动 | 
| 入力済み | 追え！ミツムシのお宝 | | Limited Time Event in v5.1 | | v5.1中的限时活动 | 
| Reminiscent Regimen: Thrill | 追憶練行・スリル編(ついおくれんぎょうスリルへん) | 追想练行·烈趣篇 | Limited Time Event in v5.1 | v5.1 期間限定イベント | v5.1中的限时活动 | add tag:[events]
| Chromatic Ode of Candies and Roses | キャンディと薔薇の歌(キャンディとばらのうた) | 彩糖与蔷薇的幻色颂 | Limited Time Event in v5.1 |v5.1 期間限定イベント | v5.1中的限时活动 | add tag:[events]
| Give Her Surprises | 彼女にサプライズを(かのじょにサプライズを) | 赠予她惊喜 | Limited Time Event in v5.1 | v5.1 期間限定イベント  | v5.1中的限时活动 | add tag:[events, story-quest]
| Rocking Carriage | ゆらゆらフロート車(ゆらゆらフロートしゃ) | 花车摇曳 | v5.1 Sub-events of the Limited Time Event "Chromatic Ode of Candies and Roses" | v5.1 期間限定イベント「キャンディと薔薇の歌」の子イベント | 限时活动「彩糖与蔷薇的幻色颂」v5.1子活动 | add tag:[events]
| Mapping Dreams and Reality | 現を見る夢(うつつをみるゆめ) | 梦与现实的映射 | v5.1 Sub-events of the Limited Time Event "Chromatic Ode of Candies and Roses" | v5.1 期間限定イベント「キャンディと薔薇の歌」の子イベント | 限时活动「彩糖与蔷薇的幻色颂」v5.1子活动 | add tag:[events]
| Shadow of the Knight's Blade | 騎士の剣光(きしのけんこう) | 骑士的剑影 | v5.1 Sub-events of the Limited Time Event "Chromatic Ode of Candies and Roses" | v5.1 期間限定イベント「キャンディと薔薇の歌」の子イベント | 限时活动「彩糖与蔷薇的幻色颂」v5.1子活动 | add tag:[events]

Character
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | type | memo |
|---|---|---|---|---|---|:-:|---|
| 入力済み | バルバトス | | The name of the god of Venti | ウェンティの魔神名 | 温迪之魔神的名字 | | 
| 入力済み | モラクス | | The name of the god of Zhongli | 鍾離の魔神名 | 钟离之魔神的名字 | | 
| 入力済み | 岩王帝君 | | Morax's honorific | モラクスの尊称 | 摩拉克斯的尊称 | |
| 入力済み | ハーゲントゥス | | The name of the god of Guizhong | 帰終の魔神名 | 归终之魔神的名字 | | 
| 入力済み | 竈神 | | Marchosius's honorific | マルコシアスの尊称 | 马克修斯的尊称 | |
| 入力済み | マルコシアス | | Guoba's former name | グゥオパァーのかつての名前 | 锅巴的原名 | | 
| 入力済み | 降魔大聖 | | Xiao's honorific | 魈の尊称 | 魈的尊称 | | 
| 入力済み | 騰蛇太元帥 | | Bosacius's honorific | 浮舎の尊称 | 浮舍的尊称 | | 
| 入力済み | 螺巻大将 | | Bonanus's honorific | 伐難の尊称 | 伐难的尊称 | | 
| 入力済み | 火鼠大将 | | Indarias's honorific | 応達の尊称 | 应达的尊称 | | 
| 入力済み | 心猿大将 | | Menogias's honorific | 弥怒の尊称 | 弥怒的尊称 | | 
| 入力済み | 留雲借風真君 | | Xianyun's adeptus name and honorific | 閑雲の称号・仙名 | 闲云的尊称、仙名|
| 入力済み | 歌塵浪市真君 | | Madame Ping's adeptus name and honorific | ピンばあやの称号・仙名 | 萍姥姥的尊称、仙名 | 
| 入力済み | 理水畳山真君 | | Jiehu's adeptus name and honorific | 接笏の称号・仙名 | 接笏的尊称、仙名 |
| 入力済み | 削月築陽真君 | | Houzhang's adeptus name and honorific | 候章の称号・仙名 | 侯章的尊称、仙名 |
| Skybracer | 移霄導天真君(いしょうどうてんしんくん) | 移霄导天真君 | |||| add tags:[liyue, character-sub]
| Rain Calmer | 銷虹霽雨真君(しょうこうせいうしんくん) | 销虹霁雨真君 | Tubby's adeptus name and honorific | マルの尊称、仙号 | 阿圆的尊称、仙号 || add tags:[liyue, Title / Other name. serenitea-pot ,character-sub]<br>塵歌壺でのマルとの会話で仙号を語る
| 入力済み | 尋瑰納琦真君 | 的尊称、仙号 | Chubby's adeptus name and honorific | ウルの尊称、仙号 | 阿嘟尊称、仙号
| Fortune Preserver | 救苦度厄真君(きゅうくどやくしんくん) | 救苦渡厄真君 | Qiqi's adeptus name |  七七の仙名 | 七七个隐士的名字 || add tags:[Title / Other name,  character-main] <br>元素爆発の時に仙名を名乗る。
| 入力済み | バアル | | The first Electro Archon. The name of the god of Makoto | 初代雷神。眞の魔神名 | 第一雷神。真之魔神的名字 | |
| 入力済み | バアルゼブル | | The second Electro Archon. The name of the god of Ei | 二代目雷神。影の魔神名 | 第二雷神。影之魔神的名字 | |
| 入力済み | 雷電将軍 | | An honorific for Makoto, Ei, and the dolls created by Ei | 眞、影および影が作成した人形の尊称 | 真、影以及影制作的人偶的尊称 | |
| Kanna Kapatcir | カンナ・カパッチリ | 菅名卡帕奇莉 | | || | add tags:[inazuma, character-sub]
| 入力済み | マハールッカデヴァータ | | The first Dendro Archon |  初代草神 | 第一草神 | | 
| 入力済み | クラクサナリデビ | | Nahida's honorific. The current Dendro Archon | ナヒーダの尊称。現在の草神  | 现任草神。纳西妲的尊称 
| 入力済み | ブエル | | The name of the god of Nahida | ナヒーダの魔神名 | 纳西妲之魔神的名字 | | 
| 入力済み | エゲリア | | The first Hydro Archon | 初代水神 | 第一水神 | |
| 入力済み | フォカロルス | | The Former Hydro Archon | 先代の水神 | 上一代的水神 | |
| Xbalanque | シュバランケ | 希巴拉克 | The first Pyro Archon | 初代炎神 | 第一火神 | | add tags:[natlan, character-sub]
| The Primordial One | 原初のあの方 | 原初的那一位 | Another name for Phanes | パネースの別の呼び方 |  法涅斯的另一个名称 | | add tags:[character-sub, how-to-call]<br>書籍「白夜国館蔵」第2巻【パネース、或いは原初のあの方】
| Phanes | パネース | 法涅斯 | | | | | add tags:[character-sub]<br>書籍「白夜国館蔵」第2巻【パネース、或いは原初のあの方】
| Ronova | ロノヴァ | 若娜瓦 | An envoy of Heavenly Reason who holds the title of "Ruler of Death" | 「死の執政」の肩書を持つ天理の使者 | 拥有「死之执政」头衔的天理使者 || add tags:[natlan, character-sub]
| Ruler of Death | 死の執政 | 死之执政 | Ronova's Title | ロノヴァの称号 | 若娜瓦的的标题 | | add tags:[Title / Other name, character-sub]
| Istaroth | イスタロト | 伊斯塔露 | An envoy of Heavenly Reason who holds the title of "Ruler of Time" | 「時間の執政」の肩書を持つ天理の使者 | 拥有「时间之执政」头衔的天理使者 || add tags:[mondstadt, inazuma, character-sub]<br>書籍「白夜国館蔵」第2巻【暗黒の三年目】に記載
| Ruler of Time | 時間の執政 | 时间之执政 | Istaroth's Title | イスタロトの称号 | 伊斯塔露的的标题 | | add tags:[Title / Other name, character-sub]<br>書籍「白夜国館蔵」第2巻【暗黒の三年目】に記載

Foods
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | memo |
|---|---|---|---|---|---|---|
| Stuffed N' Mashed Potatoes | カウサ | 夹心土豆泥

story.json5
| English | Japanese | Chinese Simplifed | Note(ja)  | Note(zh-cn)  | memo|
|---|---|---|---|---|---|
| Heavenly Principles | 天理(てんり) | 天理 | | | | 
| Adeptus name | 仙名 / 仙号(せんめい) | 仙名 / 仙号 | 仙人に対しての尊称。日本語や中国語の会話で、パイモンは留雲借風真君に申鶴の「仙名」を尋ね、塵歌壺でマルは自分の「仙号」は…と語っている。人型とそれ以外で使い分けている模様。英語ではどちらも同じ | 对隐士的尊称。在中文和日语的对话中，派蒙向留云借风真君询问申鹤的「仙名」，在尘歌壶中，阿圆说他的「仙号」是。人形生物和其他类型之间的用法似乎有所不同。在英语中，两者的待遇相同 | add tags:[liyue, Title / Other name]<br>variants: {ja: [ "せんめい", "せんごう"],},
| Adeptus power | 仙力(せんりき) | 仙力 | | | add tags:[liyue]
| Youkai powers | 妖力(ようりょく) | 妖力 | | | add tags:[lnazuma]<br>八重神子のキャラクターストーリー4や綺良々のボイスで語られている

**Comment by xicri** [comment]
Thanks!
Let me review later 🙇‍♂️

**Comment by xicri** [comment]
Thanks for waiting.

Here are my ideas for your updates:

- [Suggestion] How about replacing the English note "The name of the god of [Venti | Zhongli | ...]" with "[Venti | Zhongli | ...]'s name as a god"?
- [Question] In Raiden Shogun's note, Raiden Shogun is an honorific for "...the **dolls** created by Ei". I don't remember the story of Inazuma well, but in my understanding, there is only a single doll titled as Raiden Shogun and the other disposed dolls were not titled Raiden Shogun. I'm not sure if I understand correctly, so I leave it to you if we should keep "the dolls" or use "a doll".
- [Correction] Istaroth's note: Is there any reason why you translated 天理 as Heavenly Reason here? As you added a word, [天理 is Heavenly Principles](https://genshin-dictionary.com/ja/sustainer-of-heavenly-principles) in English.
- Heavenly Principles: In my understanding, 天理/Heavenly Principle means [天理の調停者/Sustainer of Heavenly Principle](https://genshin-dictionary.com/ja/sustainer-of-heavenly-principles), I suggest to add `character-sub` tag as well.
- Adeptus name: If there are multiple translations in Japanese, the pronunciation should be `せんめい / せんごう`.

**Comment by yasuking0304** [comment]
Thank you for your review. I would like to make the following changes:

Exclude from adding comments.
雷電将軍@Character, 天理@story.json5
 
Character
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zn-ch)  | type | memo |
|---|---|---|---|---|---|:-:|---|
| 入力済み | バルバトス | | Venti's name as a god | ウェンティの魔神名 | 温迪之魔神的名字 | | 
| 入力済み | モラクス | | Zhongli's name as a god | 鍾離の魔神名 | 钟离之魔神的名字 | | 
| 入力済み | ハーゲントゥス | | Guizhong's name as a god | 帰終の魔神名 | 归终之魔神的名字 | | 
| 入力済み | バアル | | The first Electro Archon. Makoto's name as a god | 初代雷神。眞の魔神名 | 第一雷神。真之魔神的名字 | |
| 入力済み | バアルゼブル | | The second Electro Archon. Ei's name as a god | 二代目雷神。影の魔神名 | 第二雷神。影之魔神的名字 | |
| 入力済み | ブエル | | Nahida's name as a god | ナヒーダの魔神名 | 纳西妲之魔神的名字 | | 
| 入力済み | ハボリム | | Mavuika's name as a god 
| Ronova | ロノヴァ | 若娜瓦 | An envoy of Heavenly Principle Reason who holds the title of "Ruler of Death" | 「死の執政」の肩書を持つ天理の使者 | 拥有「死之执政」头衔的天理使者 || add tags:[natlan, character-sub]
| Istaroth | イスタロト | 伊斯塔露 | An envoy of Heavenly Principle Reason who holds the title of "Ruler of Time" | 「時間の執政」の肩書を持つ天理の使者 | 拥有「时间之执政」头衔的天理使者 || add tags:[mondstadt, inazuma, character-sub]<br>書籍「白夜国館蔵」第2巻【暗黒の三年目】に記載

story.json5
| English | Japanese | Chinese Simplifed | Note(ja)  | Note(zh-cn)  | memo|
|---|---|---|---|---|---|
| adeptus name | 仙名 / 仙号(せんめい / せんごう) | 仙名 / 仙号 | 仙人に対しての尊称。日本語や中国語の会話で、パイモンは留雲借風真君に申鶴の「仙名」を尋ね、塵歌壺でマルは自分の「仙号」は…と語っている。人型とそれ以外で使い分けている模様。英語ではどちらも同じ | 对隐士的尊称。在中文和日语的对话中，派蒙向留云借风真君询问申鹤的「仙名」，在尘歌壶中，阿圆说他的「仙号」是。人形生物和其他类型之间的用法似乎有所不同。在英语中，两者的待遇相同 | add tags:[liyue, Title / Other name]<br>variants: {ja: [ "せんめい", "せんごう"],},

**Comment by xicri** [comment]
Thanks!

I guess you forgot to delete "Reason" from Ronova and Istaroth's English note:

> An envoy of Heavenly Principle ~~Reason~~ who holds the title of "Ruler of [Death|Time]"

The others look OK. Please send me a PR.
