### ISSUE TITLE
i18n ― Simplified Chinese

### ISSUE THREAD

**Issue by xicri** [xicri/genshin-langdata#52]
In this genshin-langdata repository, we need to add Simplified Chinese translations for tags.

We need to add translations for:
- tag title ([Like this line](https://github.com/xicri/genshin-langdata/pull/53/commits/25895ad74b139e0e080f5846838555113679d89a#diff-c82f98d77ca6af2b96857c1bcec6a0dbefc7bafe222d6c898542198ccf767caeR5))
  - They are shown here: ![](https://user-images.githubusercontent.com/107226297/187072476-b283cc3c-f806-4cd4-95ff-270101396ca1.png)
- Title of tag page ([Like this line](https://github.com/xicri/genshin-langdata/pull/53/commits/25895ad74b139e0e080f5846838555113679d89a#diff-c82f98d77ca6af2b96857c1bcec6a0dbefc7bafe222d6c898542198ccf767caeR9))
  - They are shown in the `<title>` of the pages like https://genshin-dictionary.com/en/tags/mondstadt/

# Translation Process

I added PR #53.

In this PR, I added placeholders for `zh-CN` translations: [25895ad](https://github.com/xicri/genshin-langdata/pull/53/commits/25895ad74b139e0e080f5846838555113679d89a)
Please add Simplified Chinese translations to the lines I added in the above commit.

I already added some translations in [a8c6261](https://github.com/xicri/genshin-langdata/pull/53/commits/a8c62612ff8e4a2bf8dd0592f390233f96a7fa84). Please review if the translation is correct.

After you added the translation, please send a PR to this `i18n-zh-CN` branch.

# Translation or Localization

I think `<title>`s should not be literally translated but "localized".
For example, the Japanese and English titles of Mondstadt are different.
- English: "Chinese & Japanese translations for words related to Mondstadt"
- Japanese: "モンドに関する言葉の英語表記一覧" (English translations for words related to Mondstadt)

Obviously, English-speaking players already know the English name of the Genshin terms, so I changed the title to "Chinese & Japanese translations..." which they may be looking for. With this change, we can acquire users who googled "(Some Genshin term) Chinese" and "(Some Genshin term) Japanese".

For Chinese translation, ~~I think the title should be like "English translations for words related to Mondstadt" as well as Japanese title. I guess there are not so many people who are interested in Japanese names, so I think we don't have to make title like "English & Japanese translations for words related to Mondstadt".
Can you give me your opinion?~~
We will make title like "English & Japanese translations for words related to Mondstadt". (Add "Japanese" in the title.)

**Comment by xicri** [comment]
@Bill-Haku I wrote an instruction for Genshin Dictionary's Chinese UI translation.

This instruction is for translating genshin-langdata repository. We also need to translate genshin-dictionary repository in addition, but I'm not ready to ask you for translating genshin-dictionary repository yet. I will tell you when I'm ready.

Let me know if you have any questions or ideas for the translation.

**Comment by Bill-Haku** [comment]
@xicri Thanks for your instruction. You wrote it carefully. I will start my work ASAP.

> For Chinese translation, I think the title should be like "English translations for words related to Mondstadt" as well as Japanese title. I guess there are not so many people who are interested in Japanese names, so I think we don't have to make title like "English & Japanese translations for words related to Mondstadt".

Regarding to this topic, I think Japanese expressions can also be interested for many Chinese Genshin players. I will translate it like "English & Japanese translations for words related to Mondstadt".

> I already added some translations in [a8c6261](https://github.com/xicri/genshin-langdata/pull/53/commits/a8c62612ff8e4a2bf8dd0592f390233f96a7fa84). Please review if the translation is correct.

I have reviewed it and it seems to be nothing wrong. I've commented it with my approval.

I will follow your instruction and I will contact you again if I have any question.

**Comment by xicri** [comment]
@Bill-Haku

> I will start my work ASAP.

Thanks, but don't rush too much. Take it easy :)

>> For Chinese translation, I think the title should be like "English translations for words related to Mondstadt" as well as Japanese title. I guess there are not so many people who are interested in Japanese names, so I think we don't have to make title like "English & Japanese translations for words related to Mondstadt".
> 
> Regarding to this topic, I think Japanese expressions can also be interested for many Chinese Genshin players. I will translate it like "English & Japanese translations for words related to Mondstadt".

OK, then let's add "Japanese" in the title.

>> I already added some translations in [a8c6261](https://github.com/xicri/genshin-langdata/pull/53/commits/a8c62612ff8e4a2bf8dd0592f390233f96a7fa84). Please review if the translation is correct.
> 
> I have reviewed it and it seems to be nothing wrong. I've commented it with my approval.

Thanks!
