### ISSUE TITLE
Rename Abdju Road to Abdju Pit in Chinese

### ISSUE THREAD

**Issue by xicri** [xicri/genshin-langdata#65]
Abdju Road (zh-CN: 舍身步道, ja: 捨身の道) is renamed to Abdju Pit (ja: 捨身の坑).
I checked the Chinese version and found the Chinese name is also renamed.

![](https://user-images.githubusercontent.com/107226297/197383512-037002ed-0db1-4ac5-85a2-ff15fc965f8d.png)

@Bill-Haku Can you update the Chinese name when you have time?
[I have renamed English and Japanese](https://github.com/xicri/genshin-langdata/commit/235fee5433adb7bc2ff034a9db8a06d1437bfdb2), but not Chinese yet.

**Comment by Bill-Haku** [comment]
In fact, it seems that the name is changed after you finish the desert theme world quest (you should know what I'm talking about but I forgot the English name of this world quest). Maybe we can keep both of them.

**Comment by xicri** [comment]
Oh, I didn't know that. Maybe the world quest is Golden Slumber / 黄金の眠り.
OK, I will keep both Abdju Road and Abdju Pit.
